import java.util.Observable;

/**
 * Classe de la vue du mode apprentissage
 * @author : vincent lamarre, guillaume docquier
 * @date : 22 septembre 2015
 */
public class VueModeApprentissage extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Constructeur a partir d'un controleur
     */
    public VueModeApprentissage(Controleur c) {
        this.controller = c;
        initComponents();
        setController();
    }
    
    //Ajout de listeners pour gerer les boutons d'actions dans le controleur
    public void setController(){        
        boutonNouveau.addActionListener(controller);
        boutonNouveau.setActionCommand("boutonNouveau");
        
        boutonRecommencer.addActionListener(controller);
        boutonRecommencer.setActionCommand("boutonRecommencer");
    }
    
    // Appelee a partir du modele
    public void update(Observable obs, Object obj) {
        Calculatrice c = (Calculatrice) obs;
        
        //Pour afficher le mode apprentissage si demande
        setVisible(c.getApprentissage());
        
        //Update l'exercice
        if (c.obtenirExerciceEnCours() != null) {            
            //Update question
            exerciceEnCours.setText(c.obtenirExerciceEnCours().obtenirQuestion());

            //Update validite
            exerciceValide.setText(c.etatSequence());
            
            //Update progres
            exerciceProgres.setValue(c.obtenirProgresApprentissage());
            
            //Update sequence
            sequence.setText(c.getSequence());
        } 
        else {
            //Valeurs par defaut
            exerciceEnCours.setText("Aucun");
            exerciceValide.setText("Inactive");
            exerciceProgres.setValue(0);
            sequence.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exerciceProgres = new javax.swing.JProgressBar();
        exerciceEnCours = new javax.swing.JLabel();
        exerciceValide = new javax.swing.JLabel();
        boutonNouveau = new javax.swing.JButton();
        boutonRecommencer = new javax.swing.JButton();
        sequence = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Exercice en cours:");

        jLabel2.setText("etat de la sequence:");

        jLabel3.setText("Progres:");

        exerciceEnCours.setText("Aucun");

        exerciceValide.setText("Inactive");

        boutonNouveau.setText("Nouvel exercice");
        boutonNouveau.setRequestFocusEnabled(false);

        boutonRecommencer.setText("Recommencer");
        boutonRecommencer.setMaximumSize(new java.awt.Dimension(144, 25));
        boutonRecommencer.setMinimumSize(new java.awt.Dimension(144, 25));
        boutonRecommencer.setRequestFocusEnabled(false);

        sequence.setEditable(false);

        jLabel4.setText("Sequence entree:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boutonNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boutonRecommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sequence)
                            .addComponent(exerciceProgres, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(exerciceEnCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exerciceValide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exerciceEnCours))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(exerciceValide))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(exerciceProgres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonNouveau)
                    .addComponent(boutonRecommencer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Controleur controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonNouveau;
    private javax.swing.JButton boutonRecommencer;
    private javax.swing.JLabel exerciceEnCours;
    private javax.swing.JProgressBar exerciceProgres;
    private javax.swing.JLabel exerciceValide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField sequence;
    // End of variables declaration//GEN-END:variables
}
