import java.util.Observable;
import java.util.Iterator;
import java.text.DecimalFormat;

/**
 * Classe de la vue principale
 * @author : vincent lamarre, guillaume docquier
 * @date : 22 septembre 2015
 */
public class VuePrincipale extends javax.swing.JFrame implements java.util.Observer {
    
    //Constructeur a partir d'un controleur
    public VuePrincipale(Controleur c) {        
        controller = c;
        initComponents();
        setController();
        setVisible(true);
    }
    
    // Appelee a partir du modele
    public void update(Observable obs, Object obj) {
        Calculatrice c = (Calculatrice) obs;
        
        //Update stackValues
        stackValue1.setText("0");
        stackValue2.setText("0");
        stackValue3.setText("0");
        stackValue4.setText("0");
        Iterator<Double> it = c.lirePile();
        int count = 0;
        while(it.hasNext()){
      		Double valeur = it.next();
                count++;
                switch(count){
                    case 1: stackValue1.setText(valeur.toString());break;
                    case 2: stackValue2.setText(stackValue1.getText());stackValue1.setText(valeur.toString());break;
                    case 3: stackValue3.setText(stackValue2.getText());stackValue2.setText(stackValue1.getText());stackValue1.setText(valeur.toString());break;
                    case 4: stackValue4.setText(stackValue3.getText());stackValue3.setText(stackValue2.getText());stackValue2.setText(stackValue1.getText());stackValue1.setText(valeur.toString());break;
                }
                //Empeche l'affichage de .0 si le chiffre est entier
                DecimalFormat decimalFormat=new DecimalFormat("#.######"); //6 decimales max, editable
                Double SV1 = Double.valueOf(stackValue1.getText());
                stackValue1.setText(decimalFormat.format(SV1));
        }        
        
        //Update boutonApprentissage
        if (c.getApprentissage())
            boutonToggleApprentissage.setText("Actif");
        else boutonToggleApprentissage.setText("Inactif");
    }    
    
    //Ajout de listeners pour gerer les boutons d'actions dans le controleur (operateurs, clear, enter, etc)
    public void setController(){        
        boutonClear.addActionListener(controller);
        boutonClear.setActionCommand("boutonClear");
        
        boutonDiv.addActionListener(controller);
        boutonDiv.setActionCommand("boutonDiv");
        
        boutonEnter.addActionListener(controller);
        boutonEnter.setActionCommand("boutonEnter");
        
        boutonMoins.addActionListener(controller);
        boutonMoins.setActionCommand("boutonMoins");
        
        boutonMult.addActionListener(controller);
        boutonMult.setActionCommand("boutonMult");
        
        boutonPlus.addActionListener(controller);
        boutonPlus.setActionCommand("boutonPlus");
        
        boutonToggleApprentissage.addActionListener(controller);
        boutonToggleApprentissage.setActionCommand("boutonToggleApprentissage");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouton2 = new javax.swing.JButton();
        bouton3 = new javax.swing.JButton();
        bouton4 = new javax.swing.JButton();
        bouton5 = new javax.swing.JButton();
        boutonPlus = new javax.swing.JButton();
        bouton6 = new javax.swing.JButton();
        boutonMoins = new javax.swing.JButton();
        bouton7 = new javax.swing.JButton();
        boutonMult = new javax.swing.JButton();
        bouton8 = new javax.swing.JButton();
        boutonDiv = new javax.swing.JButton();
        bouton9 = new javax.swing.JButton();
        boutonClear = new javax.swing.JButton();
        boutonToggleApprentissage = new javax.swing.JToggleButton();
        boutonEnter = new javax.swing.JButton();
        labelApprentissage = new javax.swing.JLabel();
        bouton1 = new javax.swing.JButton();
        bouton0 = new javax.swing.JButton();
        boutonVirgule = new javax.swing.JButton();
        stackValue4 = new javax.swing.JTextField();
        stackValue3 = new javax.swing.JTextField();
        stackValue2 = new javax.swing.JTextField();
        stackValue1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bouton2.setText("2");
        bouton2.setRequestFocusEnabled(false);
        bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton2ActionPerformed(evt);
            }
        });

        bouton3.setText("3");
        bouton3.setRequestFocusEnabled(false);
        bouton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton3ActionPerformed(evt);
            }
        });

        bouton4.setText("4");
        bouton4.setRequestFocusEnabled(false);
        bouton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton4ActionPerformed(evt);
            }
        });

        bouton5.setText("5");
        bouton5.setRequestFocusEnabled(false);
        bouton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton5ActionPerformed(evt);
            }
        });

        boutonPlus.setText("+");
        boutonPlus.setRequestFocusEnabled(false);

        bouton6.setText("6");
        bouton6.setRequestFocusEnabled(false);
        bouton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton6ActionPerformed(evt);
            }
        });

        boutonMoins.setText("-");
        boutonMoins.setRequestFocusEnabled(false);

        bouton7.setText("7");
        bouton7.setRequestFocusEnabled(false);
        bouton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton7ActionPerformed(evt);
            }
        });

        boutonMult.setText("*");
        boutonMult.setRequestFocusEnabled(false);

        bouton8.setText("8");
        bouton8.setRequestFocusEnabled(false);
        bouton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton8ActionPerformed(evt);
            }
        });

        boutonDiv.setText("/");
        boutonDiv.setRequestFocusEnabled(false);

        bouton9.setText("9");
        bouton9.setRequestFocusEnabled(false);
        bouton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton9ActionPerformed(evt);
            }
        });

        boutonClear.setText("C");
        boutonClear.setRequestFocusEnabled(false);

        boutonToggleApprentissage.setText("Inactif");
        boutonToggleApprentissage.setRequestFocusEnabled(false);

        boutonEnter.setText("ENTER");
        boutonEnter.setRequestFocusEnabled(false);

        labelApprentissage.setText("Mode d'apprentissage:");

        bouton1.setText("1");
        bouton1.setFocusPainted(false);
        bouton1.setRequestFocusEnabled(false);
        bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton1ActionPerformed(evt);
            }
        });

        bouton0.setText("0");
        bouton0.setRequestFocusEnabled(false);
        bouton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton0ActionPerformed(evt);
            }
        });

        boutonVirgule.setText(".");
        boutonVirgule.setRequestFocusEnabled(false);
        boutonVirgule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonVirguleActionPerformed(evt);
            }
        });

        stackValue4.setEditable(false);
        stackValue4.setBackground(new java.awt.Color(255, 255, 255));
        stackValue4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stackValue4.setText("0");
        stackValue4.setPreferredSize(new java.awt.Dimension(24, 25));

        stackValue3.setEditable(false);
        stackValue3.setBackground(new java.awt.Color(255, 255, 255));
        stackValue3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stackValue3.setText("0");
        stackValue3.setPreferredSize(new java.awt.Dimension(24, 25));

        stackValue2.setEditable(false);
        stackValue2.setBackground(new java.awt.Color(255, 255, 255));
        stackValue2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stackValue2.setText("0");
        stackValue2.setPreferredSize(new java.awt.Dimension(24, 25));

        stackValue1.setEditable(false);
        stackValue1.setBackground(new java.awt.Color(255, 255, 255));
        stackValue1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stackValue1.setText("0");
        stackValue1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackValue1.setPreferredSize(new java.awt.Dimension(24, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bouton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bouton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bouton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bouton7)
                            .addComponent(boutonClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bouton8)
                            .addComponent(bouton0, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bouton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutonVirgule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boutonMoins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boutonDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonMult, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                            .addComponent(boutonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelApprentissage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonToggleApprentissage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bouton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bouton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bouton6))
                    .addComponent(stackValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stackValue2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stackValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stackValue4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stackValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stackValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stackValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stackValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton1)
                            .addComponent(bouton2)
                            .addComponent(bouton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton4)
                            .addComponent(bouton5)
                            .addComponent(bouton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton7)
                            .addComponent(bouton8)
                            .addComponent(bouton9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boutonPlus)
                            .addComponent(boutonMult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boutonMoins)
                            .addComponent(boutonDiv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonEnter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonVirgule)
                    .addComponent(bouton0)
                    .addComponent(boutonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApprentissage)
                    .addComponent(boutonToggleApprentissage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton1ActionPerformed
        controller.addToSequence("1");
    }//GEN-LAST:event_bouton1ActionPerformed

    private void bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton2ActionPerformed
        controller.addToSequence("2");
    }//GEN-LAST:event_bouton2ActionPerformed

    private void boutonVirguleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonVirguleActionPerformed
        controller.addToSequence(".");
    }//GEN-LAST:event_boutonVirguleActionPerformed

    private void bouton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton3ActionPerformed
        controller.addToSequence("3");
    }//GEN-LAST:event_bouton3ActionPerformed

    private void bouton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton4ActionPerformed
        controller.addToSequence("4");
    }//GEN-LAST:event_bouton4ActionPerformed

    private void bouton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton5ActionPerformed
        controller.addToSequence("5");
    }//GEN-LAST:event_bouton5ActionPerformed

    private void bouton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton6ActionPerformed
        controller.addToSequence("6");
    }//GEN-LAST:event_bouton6ActionPerformed

    private void bouton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton7ActionPerformed
        controller.addToSequence("7");
    }//GEN-LAST:event_bouton7ActionPerformed

    private void bouton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton8ActionPerformed
        controller.addToSequence("8");
    }//GEN-LAST:event_bouton8ActionPerformed

    private void bouton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton9ActionPerformed
        controller.addToSequence("9");
    }//GEN-LAST:event_bouton9ActionPerformed

    private void bouton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton0ActionPerformed
        controller.addToSequence("0");
    }//GEN-LAST:event_bouton0ActionPerformed
    
    private Controleur controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton0;
    private javax.swing.JButton bouton1;
    private javax.swing.JButton bouton2;
    private javax.swing.JButton bouton3;
    private javax.swing.JButton bouton4;
    private javax.swing.JButton bouton5;
    private javax.swing.JButton bouton6;
    private javax.swing.JButton bouton7;
    private javax.swing.JButton bouton8;
    private javax.swing.JButton bouton9;
    private javax.swing.JButton boutonClear;
    private javax.swing.JButton boutonDiv;
    private javax.swing.JButton boutonEnter;
    private javax.swing.JButton boutonMoins;
    private javax.swing.JButton boutonMult;
    private javax.swing.JButton boutonPlus;
    private javax.swing.JToggleButton boutonToggleApprentissage;
    private javax.swing.JButton boutonVirgule;
    private javax.swing.JLabel labelApprentissage;
    private javax.swing.JTextField stackValue1;
    private javax.swing.JTextField stackValue2;
    private javax.swing.JTextField stackValue3;
    private javax.swing.JTextField stackValue4;
    // End of variables declaration//GEN-END:variables
}
